patient_list/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

     resources :patients

end

patient_list/app/models/patient.rb
class Patient < ActiveRecord::Base
end

patient_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

patient_list/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @patients = Patient.all
end
end

patient_list/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def show
    @patient = Patient.find params[:id]
  end

  def new
    @patient = Patient.new
end

def create
  @patient = Patient.create que_params
  redirect_to root_path
end

def edit
  @patient = Patient.find params[:id]
  end

  def update
    @patient = Patient.find params[:id]
    @patient.update_attributes que_params
    redirect_to root_path
  end

  def destroy
    @patient = Patient.find params[:id]
    @patient.delete
    redirect_to root_path
  end


private

def que_params
  params.require(:patient).permit(
   :first,
   :last,
   :birth,
   :description,
   :gender,
   :blood,
   )
end
end

patient_list/app/helpers/application_helper.rb
module ApplicationHelper
end

patient_list/app/helpers/home_helper.rb
module HomeHelper
end

patient_list/app/helpers/patients_helper.rb
module PatientsHelper
end

patient_list/app/views/home/index.html.erb
<h1>A.C.M.E Hospital Patient Tracking System</h1>
<%= link_to "New Patient", new_patient_path %>
<br>
<br>
<% @patients.each do |patients| %>

<%= link_to patients.first, patient_path(patients) %>
<%= link_to "Edit", edit_patient_path(patients) %>
<%= link_to "Delete", patient_path(patients), method: :delete %>
<br>
<% end %>

patient_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatientList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

patient_list/app/views/patients/edit.html.erb
<h1>Edit Contact</h1>

<%= form_for @patient do |f| %>
  <%=f.label :first %>
  <%=f.text_field :first %>
  <%=f.label :last %>
  <%=f.text_field :last %>
  <%=f.label :birth %>
  <%=f.date_select :birth %>
  <%=f.label :description %>
  <%=f.text_field :description %>
  <%=f.label :gender %>
  <%=f.text_field :gender %>
  <%=f.label :blood %>
  <%=f.text_field :blood %>
  <br>
  <%= f.submit %>
  <% end %>

patient_list/app/views/patients/new.html.erb
<ht>New Patient</h1>

  <%= form_for @patient do |f| %>
  <%= f.label :first %>
  <%= f.text_field :first %>
  <%= f.label :last %>
  <%= f.text_field :last %>
  <%= f.label :birth %>
  <%= f.date_select :birth %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :gender %>
  <%= f.text_field :gender  %>
  <%= f.label :blood %>
  <%= f.text_field :blood %>
  <br>
  <%= f.submit %>
  <% end %>

patient_list/app/views/patients/show.html.erb
<h1>Show data</h1>

<%= @patient.first %>
<%= @patient.last %>
<%= @patient.birth %>
<%= @patient.description %>
<%= @patient.gender %>
<%= @patient.blood %>
<%= link_to "Home", root_path %>